# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Spring Boot CI

on: [push, pull_request]

jobs:
  build_and_test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2 

    - name: Build project with Maven on Windows
      if: runner.os == 'windows'
      run: |
        ./mvnw.cmd clean verify
        ./mvnw.cmd clean install
        ./mvnw.cmd test

    - name: Build project with Maven on *NIX
      if: runner.os != 'windows'
      run: |
        ./mvnw clean verify
        ./mvnw clean install
        ./mvnw test
        awk -F, '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
        bash <(curl -s https://codecov.io/bash)
